name: Build monzo-exporter
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      timestamp: ${{ steps.tag.outputs.timestamp }}
    steps:
      - name: Get timestamp
        id: tag
        run: |
          timestamp="$(date +%s)" 
          echo "timestamp=$timestamp">> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ${{ github.workspace }}/
          file: ${{ github.workspace }}/Dockerfile
          tags: ${{ secrets.GHCR_REGISTRY }}/monzo-exporter:dev-${{ steps.tag.outputs.timestamp }}

  trivy:
    name: Trivy scan
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Pull dev image
        run: docker pull ${{ secrets.GHCR_REGISTRY }}/monzo-exporter:dev-${{ needs.build.outputs.timestamp }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.GHCR_REGISTRY }}/monzo-exporter:dev-${{ needs.build.outputs.timestamp }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

  push:
    name: Push stable version
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.ref_name == 'main' }}
    needs:
      - build
      - trivy
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Pull dev image
        run: docker pull ${{ secrets.GHCR_REGISTRY }}/monzo-exporter:dev-${{ needs.build.outputs.timestamp }}

      - name: Docker retag
        run: docker tag ${{ secrets.GHCR_REGISTRY }}/monzo-exporter:dev-${{ needs.build.outputs.timestamp }} ${{ secrets.GHCR_REGISTRY }}/monzo-exporter:stable-${{ needs.build.outputs.timestamp }}

      - name: Docker push
        run: docker push ${{ secrets.GHCR_REGISTRY }}/monzo-exporter:stable-${{ needs.build.outputs.timestamp }}